config/routes.rb
Rails.application.routes.draw do

  # дергаем спец. девайзовский метод, который генерит все нужные ему пути
  devise_for :users

  root "events#index"

  resources :events do
    # вложенный ресурс комментов
    resources :comments, only: [:create, :destroy]

    # вложенный ресурс подписок (см. rake routes)
    resources :subscriptions, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions, source: :user

  validates :user, presence: true

  validates :title, presence: true, length: {maximum: 255}
  validates :address, presence: true
  validates :datetime, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  EVENT_PER_PAGE = 3
  # Задаем объект @event для тех действий, где он нужен
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_event, only: [:show]
  before_action :set_current_user_event, only: [:edit, :update, :destroy]

  def index
    @page = params.fetch(:page,0).to_i
    @events = Event.offset(@page * EVENT_PER_PAGE).limit(EVENT_PER_PAGE)
  end

  def show
    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
  end

  def new
    @event = current_user.events.build
  end

  def edit
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      # Используем сообщение из файла локалей ru.yml
      # controllers -> events -> created
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: I18n.t('controllers.events.destroyed')
  end

  private

  def set_current_user_event
    @event = current_user.events.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<%# Паршиал для отображения инфы об отдельном событии %>
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">

    <%= content_tag 'div', '', class: 'event-background',
      style: "background-image: url(#{asset_path('event_thumb.jpg')})" %>

    <div class="thumbnail-inner event-info-inner">
      <div class="caption">
        <div class="event-description">
          <h3><%= link_to event.title, event_path(event) %></h3>
          <h3>
            <small><%= l event.datetime, format: :short %></small>
          </h3>
          <div class="buffer-both"><%= event.address %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%# Паршиал дляотображения формы создания нового события %>
<%= form_for(@event) do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @event} %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :datetime %>
    <p><%= f.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit t('button.save'), class: 'btn btn-primary' %>
    <%= t('or') %>
    <%= link_to t('link.back'), :back %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>
  <%= t('header.edit_events') %>
</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<h1>События</h1>

<div class="buffer-both">
  <%= link_to t('button.create_event'), new_event_path, class: 'btn btn-success' %>
</div>

<div class="row buffer-bottom">
  <%# Рендерим сразу массив событий, каждый в паршиале 'events/event' %>
  <%= render partial: 'events/event', collection: @events %>
</div>

<div class="pagination pagination-lg justify-content-center">
  <%= link_to "Last Page", events_path(page: @page - 1)  %>
  |
  <%= link_to "Next Page", events_path(page: @page + 1)  %>
</div>

app/views/events/new.html.erb
<h1>Новое событие</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<div class="event">
  <div class="event-info row">
    <div class="col-md-12">
      <%= content_tag 'div', '', class: 'event-background',
                      style: "background-image: url(#{asset_path('event.jpg')})" %>

      <div class="event-info-inner row">
        <div class="col-md-6">
          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= l @event.datetime, format: :short %></h3>
            <h3>
              <small>
                <%= link_to @event.address, "https://yandex.ru/maps/?text=#{@event.address}" %>
              </small>
            </h3>
            <p><%= @event.description %></p>
          </div>

          <% if current_user_can_edit?(@event) %>
            <div class="buffer-top buffer-bottom">

              <%= link_to t('button.update'), edit_event_path(@event),
                          class: 'btn btn-primary btn-custom-size' %>

              <%= link_to t('button.delete'), event_path(@event),
                          method: :delete,
                          data: {confirm: t('confirm.delete',
                                            resource: @event.class.model_name.human.downcase)},
                          class: 'btn btn-danger btn-custom-size' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <div class="event-comments buffer-top">
        <%= render partial: 'comments/form',
                   locals: {comment: @new_comment || @event.comments.build} %>

        <div class="buffer-both">
          <%= render partial: 'comments/comment',
                     collection: @event.comments.except(@new_comment) %>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="event-owner">
        <h4><%= t('subscriptions.subscription.show_organizer') %></h4>
        <p><%= render partial: 'users/user', object: @event.user %></p>
      </div>
      <div class="event-subscriptions">
        <h4><%= t('subscriptions.subscription.show_subscribed') %></h4>
        <div>
          <p>
            <%= render partial: 'subscriptions/subscription',
                       collection: @event.subscriptions.except(@new_subscription) %>
          </p>
        </div>
      </div>
      <div class="event-subscription-form">
        <% unless @event.user == current_user %>
          <div>
            <%= render partial: 'subscriptions/form', locals: {
                subscription: @new_subscription || @event.subscriptions.build
            } %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>